apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato-clone
  labels:
    app: zomato-clone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zomato-clone
  template:
    metadata:
      labels:
        app: zomato-clone
    spec:
      containers:
      - name: zomato-clone
        image: iamtejas23/zomato-clone:latest # Docker Hub image
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
