apiVersion: v1
kind: Service
metadata:
  name: zomato-clone-service
  labels:
    app: zomato-clone
spec:
  type: NodePort
  selector:
    app: zomato-clone
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
